INSERT INTO categoria(nombre_categoria) VALUES('arboles')
INSERT INTO categoria(nombre_categoria) VALUES('Luces')
INSERT INTO categoria(nombre_categoria) VALUES('Adornos')
INSERT INTO categoria(nombre_categoria) VALUES('Postales')
INSERT INTO categoria(nombre_categoria) VALUES('Belenes')